"""add importance

Revision ID: 8a88a5949a88
Revises: 34a6f4ddb922
Create Date: 2022-12-17 01:15:11.538112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a88a5949a88'
down_revision = '34a6f4ddb922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note_model', sa.Column('importance', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note_model', 'importance')
    # ### end Alembic commands ###
